# Generated by Django 4.0.2 on 2022-02-19 15:35

import Petstagram.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[Petstagram.common.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[Petstagram.common.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)])),
                ('picture', models.URLField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do Not Show', 'Do Not Show')], max_length=11, null=True)),
            ],
        ),
    ]
