# Generated by Django 4.0.2 on 2022-03-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_petphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
